NAME	= zombie
COMP	= c++
FLAGS	= -Wall -Wextra -Werror -std=c++98
MAIN	= main.cpp Weapon.cpp Weapon.hpp HumanA.cpp HumanA.hpp HumanB.cpp HumanB.hpp

all:
	$(COMP) $(FLAGS) $(MAIN)

clear:
	rm -rf $(NAME)

