# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: esilva-s <esilva-s@student.42sp.org.br>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/26 20:52:30 by esilva-s          #+#    #+#              #
#    Updated: 2023/05/26 20:59:39 by esilva-s         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = phonebook
CC = c++
FLAGS = -std=c++98 -Wall -Wextra -Werror
SRC = main.cpp PhoneBook.hpp PhoneBook.cpp Contact.cpp Contact.hpp print_tools.cpp main.hpp

all:
	$(CC) $(FLAGS) $(SRC) 

clean:
	rm -rf a.out