NAME	= zombie
COMP	= c++
FLAGS	= -Wall -Wextra -Werror -std=c++98
MAIN	= main.cpp
SRC		= Zombie.cpp Zombie.hpp newZombie.cpp randomChump.cpp

all:
	$(COMP) $(FLAGS) $(MAIN) $(SRC)

clear:
	rm -rf $(NAME)